main/urls.py
from django.conf.urls import url

from . import views

app_name='main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^newuser/$', views.newuser, name='newuser'),
    url(r'^login/$', views.login, name='login'),
    url(r'^loginauth/$', views.loginauth, name='loginauth'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^resetpassword/$', views.resetpassword, name='resetpassword'),
    url(r'^(?P<user_id>[0-9]+)/resetauth/$', views.resetauth, name='resetauth'),
    url(r'^(?P<user_id>[0-9]+)/resetauthprocess/$', views.resetauthprocess, name='resetauthprocess'),
]

user/urls.py
from django.conf.urls import url

from . import views

app_name='user'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newpostform/$', views.newpostform, name='newpostform'),
    url(r'^(?P<post_id>[0-9]+)/newpostform/$', views.newpostformid, name='newpostformid'),
    url(r'^newpost/$', views.newpost, name='newpost'),
    url(r'^sitenamefind/$', views.sitenamefind, name='sitenamefind'),
    url(r'^sitenamelist/$', views.sitenamelist, name='sitenamelist'),
    url(r'^deletepost/$', views.deletepost, name='deletepost'),
    url(r'^(?P<user_id>[0-9]+)/$', views.search, name='search'),
    url(r'^search/$', views.searchuser, name='searchuser'),
    url(r'^viewaspublic/$', views.viewaspublic, name='viewaspublic'),
    url(r'^viewasconnected/$', views.viewasconnected, name='viewasconnected'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^customize/$', views.customize, name='customize'),
    url(r'^editsettings/$', views.editsettings, name='editsettings'),
    url(r'^editprofileimg/$', views.editprofileimg, name='editprofileimg'),
    url(r'^editbgimg/$', views.editbgimg, name='editbgimg'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^readnotifs/$', views.readnotifs, name='readnotifs'),
    url(r'^(?P<user_id>[0-9]+)/newnotif/$', views.newnotif, name='newnotif'),
    url(r'^(?P<user_id>[0-9]+)/cancelnotif/$', views.cancelnotif, name='cancelnotif'),
    url(r'^connections/$', views.connections, name='connections'),
    url(r'^get_status_twitter/$', views.get_status_twitter, name='get_status_twitter'),
    url(r'^(?P<user_id>[0-9]+)/newconnect/$', views.newconnect, name='newconnect'),
    url(r'^(?P<user_id>[0-9]+)/disconnect/$', views.disconnect, name='disconnect'),
    url(r'^custom/$', views.custom, name='custom'),
    url(r'^customsubmit/$', views.customsubmit, name='customsubmit'),
    url(r'^logout/$', views.logout, name='logout'),
]

webapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^user/', include('user.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

"""
    User:
    - Represents the accounts registered by the users within the application.

    Attributes:
    - username (unique)
    - password
    - email (unique)
    - displayname (not unique)
    - description
    - vis (integer field - public/1 or private/0)
    - profileImg
    - bgImg
    - useBg (unused attribute)
"""
class User(models.Model):
    VIS_CHOICES=(
        (1, 'Public'),
        (0, 'Private'),
    )
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField()
    displayname = models.CharField(max_length=50)
    description = models.CharField(max_length=200, blank=True)
    vis = models.PositiveSmallIntegerField(choices=VIS_CHOICES, default=1)
    profileImg = models.ImageField(upload_to='pic/', default = 'pic/default.jpg')
    bgImg = models.ImageField(upload_to='bg/', default = 'bg/default.jpg')  #change to imagefield?
    useBg = models.BooleanField()

    def __str__(self):
        return self.username

"""
    Post:
    - Represents the accounts of other site domains added by the users into their profiles.

    Attributes:
    - user (reference to user's ID as foreign key)
    - sitename (name of the site domain of the account added)
    - siteusername (username used on that site domain)
    - email (email used on that site domain - stored as a record of the user's login credential)
    - url
    - post_date (date of the latest update of the post)
    - usage (integer field - Most used/3, Moderately used/2, Least used/1, On hiatus/0)
    - description
    - vis (integer field - public/2, reserved/1, private/0)
    - logo
"""
class Post(models.Model):
    VIS_CHOICES=(
        (2, 'Public'),
        (1, 'Reserved'),
        (0, 'Private'),
    )
    USAGE_CHOICES=(
        (3, 'Most used'),
        (2, 'Moderately used'),
        (1, 'Least used'),
        (0, 'On hiatus'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sitename = models.CharField(max_length=50)
    siteusername = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    url = models.URLField(blank=True)
    post_date = models.DateTimeField(auto_now=True)
    usage = models.PositiveSmallIntegerField(choices=USAGE_CHOICES, default=3)
    category = models.CharField(max_length=50, blank=True)
    description = models.CharField(max_length=100, blank=True)
    vis = models.PositiveSmallIntegerField(choices=VIS_CHOICES, default=2)
    logo = models.ImageField(upload_to='logo/', default = 'logo/default/pizza.png') #change to imagefield?

    def __str__(self):
        return str(self.id) + ' ' + self.sitename

    def was_posted_recently(self):
        return self.post_date >= timezone.now() - datetime.timedelta(days=1)

    def has_url(self):
        return bool(self.url)

    def has_email(self):
        return bool(self.email)

    def formatted_post_date(self):
        month = self.post_date.strftime('%b')
        day = str(self.post_date.day)
        result = month + " " + day
        return result


"""
    Notification
    - Generated when users send others a connection request or a connection request has been accepted.

    Attributes:
    - fromuser (id of the user who sent the connection request)
    - touser (id of the user who received the connection request)
    - is_read (boolean field)
    - is_accepted (boolean field)
    - notif_date (date of sending the connection request. This attribute is updated when the connection request is accepted. The new value is the date of which the request is accepted)
    - message (unused attribute)
"""
class Notification(models.Model):
    fromuser = models.PositiveIntegerField()
    touser = models.PositiveIntegerField()
    is_read = models.BooleanField(default=False)
    is_accepted = models.BooleanField(default=False)
    notif_date = models.DateTimeField(default=datetime.datetime.now())
    message = models.CharField(max_length=100)
    def __str__(self):
        return str(self.notif_date)

    def from_username(self):
        u = User.objects.get(id=self.fromuser)
        return u.username

    def to_username(self):
        u = User.objects.get(id=self.touser)
        return u.username

    def from_user_profileimg(self):
        u = User.objects.get(id=self.fromuser)
        return u.profileImg

    def to_user_profileimg(self):
        u = User.objects.get(id=self.touser)
        return u.profileImg


"""
    Connection
    - Represents the establishment of connection between two users.

    Attributes:
    - fromuser (id of the user who sent the connection request)
    - touser (id of the user who received and accepted the connection request)
"""
class Connection(models.Model):
    fromuser = models.PositiveIntegerField()
    touser = models.PositiveIntegerField()

user/forms.py
from django import forms
from django.forms import ModelForm

from .models import User, Post

#VERY IMPORTANT
#http://stackoverflow.com/questions/2010747/empty-request-files-with-django-upload-forms
"""
class PostForm_2(forms.Form):
    postid = forms.CharField(max_length=100)
    sitename = forms.CharField(max_length=50)
    siteusername = forms.CharField(max_length=50)
    email = forms.EmailField()
    url = forms.URLField()
    usage = forms.CharField(max_length=50)
    category = forms.CharField(max_length=50)
    description = forms.CharField(max_length=100)
    vis = forms.CharField(max_length=50)
    logo = forms.ImageField()
"""


"""
    PostForm
    - Form used for both inserting and editing posts.
    - Based on the Post object.
    (See also: models.py)
"""
class PostForm(ModelForm):
    postid = forms.CharField(max_length=100)
    class Meta:
        model = Post
        fields = ['sitename', 'siteusername', 'email', 'url', 'category', 'description', 'usage', 'vis', 'logo']
        exclude = ['category']
        labels = {
            'sitename': 'Site name',
            'siteusername': 'Username',
            'vis' : 'Visibility',
        }
        widgets = {
            'sitename': forms.TextInput(attrs={'list': 'sitenamelist', 'autocomplete': 'off'}),
            'vis': forms.RadioSelect(attrs={'class': 'radiobutton'}),
            'usage': forms.RadioSelect(attrs={'class': 'radiobutton'}),
        }

"""
class AccountForm_2(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'value': 'your username'}))
    password = forms.CharField(max_length=50)
    email = forms.EmailField()
    displayname = forms.CharField(max_length=50)
    description = forms.CharField(max_length=200)
    vis = forms.CharField(max_length=50)
    profileImg = forms.ImageField() #change to imagefield?
    bgImg = forms.CharField(max_length=200)   #change to imagefield?
    useBg = forms.CharField(max_length=50)
"""

"""
    AccountForm
    - Form used for the settings page to edit the user's account settings.
    - Based on the User object.
    (See also: models.py)
"""
class AccountForm(ModelForm):
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(), label='Password (required)')
    new_password = forms.CharField(max_length=50, required=False, widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'email', 'displayname', 'description', 'vis', 'profileImg', 'bgImg', 'useBg']
        exclude = ['profileImg', 'bgImg', 'useBg']
        labels = {
            'vis' : 'Visibility',
            'profileImg' : 'Profile image',
            'bgImg' : 'Background image',
            'useBg' : 'Enable background',
        }
        widgets = {
            'vis': forms.RadioSelect(attrs={'class': 'radiobutton'}),
        }

user/templates/user/custom.html
{% extends 'main/layout.html' %}

{% block title %}Custom widgets {% endblock %}

{% block js %}
<script>
$(document).ready(function() {
  $('#togglecheckbox').click(function() {
      var toggle = this.checked;
      checkboxes = document.getElementsByName('customchoice');
      $.each(checkboxes, function() {
        $(this).attr('checked', toggle);
      })
  })

  $('#customform').submit(function() {
    values = []
    $('#customform input:checked').each(function(i) {
      values[i] = $(this).val();
    })
    result = values.join(", ");
    $.ajax({
        url: "{% url 'user:customsubmit' %}",
        type: 'get',
        data: {'customchoice': result},
        success: function(data) {
          //alert(data);
          $('#customwidgets').html(data);
        },
        failure: function(data) {
            alert('Got an error dude');
        }
    });
    return false; //!!!!
  })
})
</script>
{% endblock %}

{% block content %}
<div class="realcontent">
  <h1>Custom widgets</h1>
  <span class="realcontentlinks">
  <a href="{% url 'user:settings' %}" class="hvr-grow">Back to settings <i class="fa fa-cog" aria-hidden="true"></i></a></span>
  <p>Generate widgets from the accounts you've listed on your profile:
  <br/>* only accounts with URLs will be listed.</p>
  <input type="checkbox" id="togglecheckbox"/> Toggle All
  <br/>
  <form id="customform" method="get">
      {% for p in posts %}
      <div class="post customchoicebox"><input type="checkbox" name="customchoice" value="{{ p.id }}" /><img src="/media/{{ p.logo }}">
        <div><a href="{{ p.url }}"><span class="post-siteusername">{{ p.siteusername }}</span></a><br/><span class="post-sitename">{{ p.sitename }}</span>
          {% if p.vis == 0 %}
          <div class="post-bottomright">
            <i class="fa fa-lock"></i><span class="post-bottomright-text transparent">{{ p.get_vis_display }}</span>
          </div>
          {% elif p.vis == 1 %}
          <div class="post-bottomright">
            <i class="fa fa-unlock-alt"></i><span class="post-bottomright-text transparent">{{ p.get_vis_display }}</span>
          </div>
          {% endif %}
      </div>
      </div>
      {% endfor %}
    <center><button class="submitbutton hvr-grow" type="submit"><span class="buttonleftfont oswald-font">Generate code</span> <i class="fa fa-code fa-2x"></i></button></center>
  </form>
  <br/>
  <div id="customwidgets">{{ result }}</div>
  <br/><br/>

</div>
{% endblock %}

user/templates/user/customize.html
{% extends 'main/layout.html' %}

{% block title %}Customization {% endblock %}

{% block css %}
    {% with searcheduser=user %}
    {% include 'user/profilecss.html' %}
    {% endwith %}
{% endblock %}

{% block content %}
<div class="contentboxbg"><div class="contentboxbgoverlay">
  <form action="{% url 'user:editbgimg' %}" method="post" enctype="multipart/form-data" class="bgimgform">
  {% csrf_token %}
    <input type="file" name="bgImg" class="bgimginput" id="bgimginput"/>
    <i class="fa fa-pencil fa-2x bgimginputicon" aria-hidden="true"></i>
    <button id="bgimginputbutton" class="connectbutton orange transparent hover-green" type="submit">Save background</button>
  </form>
  </div>
</div>
  <form action="{% url 'user:editprofileimg' %}" method="post" enctype="multipart/form-data" id="profileimgform">
  {% csrf_token %}
    <div class="profileimgouterdiv">
      <div style="background:url('/media/{{ user.profileImg }}') no-repeat center; background-size:158px 158px;" id="contentprofileimg"/></div>
      <div class="profileimginputdiv profileimgrounded">
        <input type="file" name="profileImg" class="profileimginput profileimgrounded" id="profileimginput"/>
        <i class="fa fa-pencil fa-2x profileimginputicon" aria-hidden="true"></i>
      </div>
    </div>
    <div class="contentboxdetails">
      <button class="connectbutton orange transparent hover-green" id="profileimginputbutton" type="submit">Save profile image</button>
    </div>
  </form>

<div class="realcontent">
  <div class="customizecontent">
  <h1>Customization</h1>
  <span class="realcontentlinks">
  <a href="{% url 'user:settings' %}" class="hvr-grow">Back to settings <i class="fa fa-cog" aria-hidden="true"></i></a></span>
  <p>Hover over your header or profile images to change them.
  <br/>The maximum upload size is 300KB for profile image and 1.5MB for header image.</p>
  {% if message %}<p class="message">{{ message }}</p>{% endif %}
</div>
</div>
{% endblock %}

user/templates/user/customwidgethtml.html
<h2>Preview</h2>
<div class="customwidgetbox">
  <div class="customwidgetcol">
  {% autoescape off %}
  <textarea onclick="this.focus();this.select()">
    <div style="border:1px solid #e4e4e4; width:100%; padding:15px; color:#777; font-family:calibri; font-size:1em;">
      Links:<br/>
    {% for p in posts %}<a href="{{ p.url }}"><img src="/media/{{ p.logo }}" style="width:20px;height:20px;" alt="{{ p.sitename }}"/></a> {% endfor %}
    </div>
  </textarea>
  {% endautoescape %}
  </div><div class="customwidgetcol">
    <div style="border:1px solid #e4e4e4; width:100%; padding:15px; color:#777; font-family:calibri; font-size:1em;">
      Links:<br/>
    {% for p in posts %}<a href="{{ p.url }}"><img src="/media/{{ p.logo }}" style="width:20px;height:20px;" alt="{{ p.sitename }}"/></a> {% endfor %}
    </div>
  </div>
</div>

user/templates/user/index.html
{% extends 'main/layout.html' %}

{% block title %}Profile {% endblock %}

{% if user %}

    {% block css %}
    {% with searcheduser=user %}
    {% include 'user/profilecss.html' %}
    {% endwith %}
    {% endblock %}
{% endif %}

{% block outsidecontent %}{% include 'user/postlistform.html' %}{% endblock %}

{% block content %}
  {% if user %}
    {% with searcheduser=user %}
    {% include 'user/profiledetails.html '%}
    </div>
    {% endwith %}
    <div class="realcontent">
      {% with searcheduser=user %}
      {% include 'user/postlist.html' %}
      {% endwith %}
    </div>

  {% endif %}
{% endblock %}

user/templates/user/notifications.html
{% extends 'main/layout.html' %}

{% block title %}Notifications {% endblock %}

{% block js %}
<script>
$.ajax({
    url: '/user/readnotifs',
    type: 'get',
    success: function(data) {
        //alert(data);
    },
    failure: function(data) {
        alert('Got an error dude');
    }
});
</script>
{% endblock %}

{% block content %}
<div class="realcontent">
  <h1>Notifications</h1>
  Notifications will appear in your inbox when a user sends you a connection request, or when a user has acceted your connection request.
  <br/><br/>
  {% if toread or readnotifs %}
    {% if toread %}
      {% with notifs=toread class='toread' %}
        {% include 'user/notifdetails.html' %}
      {% endwith %}
    {% endif %}
    {% with notifs=readnotifs class='readnotifs' %}
      {% include 'user/notifdetails.html' %}
    {% endwith %}
  {% else %}
  <p class="message">You do not have any notifications yet.</p>
  {% endif %}
</div>

{% endblock %}

user/templates/user/postdetails.html
{% if forloop.first %}<section><h2>{{ post.get_usage_display }}</h2>{% endif %}
<div class="postborder">
<div class="post">
  <div class="post-img">
    <img src="/media/{{ post.logo }}" class="hvr-grow">
  </div><div class="post-text">
    <div class="post-text-header">
    {% if post.has_url %}<a href="{{ post.url }}">{% endif %}
      <span class="post-floatleft post-siteusername">{{ post.siteusername }} </span>
    {% if post.has_url %}</a>{% endif %}
    <span class="post-sitename">{% if post.siteusername %} | {% endif %}{{ post.sitename }}</span>
    </div>
    <p>{{ post.description }}<br/></p>
  </div>
  {% if ownprofile %}
    <div class="bottom">
    <form action="{% url 'user:deletepost' %}" method="post" class="deletepostform" enctype="multipart/form-data">
      {% csrf_token %}
      <input name="deletepostid" type="text" value="{{post.id}}" class="hidden"/>
      <button class="fa fa-times deletepostbutton hvr-grow"></button>
    </form><button class="fa fa-pencil editpostbutton hvr-grow" id="{{post.id}}"></button>
    </div>
  {% endif %}
</div>
{% if ownprofile %}
    <span class="post-floatleft post-bottomtext">{% if post.has_email %}{{ post.email }} <br/>{% endif %}<span class="post-postdate transparent">Last updated on {{ post.formatted_post_date }}</span></span>
    {% if post.vis == 0 %}
    <div class="post-floatright post-bottomright">
      <span class="post-bottomright-text transparent">{{ post.get_vis_display }}</span><i class="fa fa-lock"></i>
    </div>
    {% elif post.vis == 1 %}
    <div class="post-floatright post-bottomright">
      <span class="post-bottomright-text transparent">{{ post.get_vis_display }}</span><i class="fa fa-unlock-alt"></i>
    </div>
    {% endif %}
{% endif %}
</div>
{% if forloop.last %}</section>{% endif %}

user/templates/user/postform.html
<table>{{ form.as_table }}</table>

user/templates/user/postlist.html
<!--
This page handles sorting of the user's account by their usage
-->

<div class="postlist">
{% if posts.mostUsed or posts.moderatelyUsed or posts.leastUsed or posts.onHiatus %}
{% for post in posts.mostUsed %}
  {% include 'user/postdetails.html' %}
{% endfor %}
{% for post in posts.moderatelyUsed %}
  {% include 'user/postdetails.html' %}
{% endfor %}
{% for post in posts.leastUsed %}
  {% include 'user/postdetails.html' %}
{% endfor %}
{% for post in posts.onHiatus %}
  {% include 'user/postdetails.html' %}
{% endfor %}
{% else %}
  {% if ownprofile %}You have not added any accounts yet.
  {% else %}This user has not added any accounts yet.
  {% endif %}
{% endif %}

{% if ownprofile %}
<center><button class="submitbutton hvr-grow" id="newpostbutton"><span class="buttonleftfont oswald-font">Add a new account</span> <i class="fa fa-plus-circle fa-2x"></i></button></center>
{% endif %}
</div>

user/templates/user/postlistform.html
{% extends 'user/postformlayout.html' %}

{% block postformheader %}Add account information{% endblock %}

{% block postformcontent %}
<form action="{% url 'user:newpost' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div id="theform"><table id="postform">{{ form.as_table }}</table></div>
  <span id="sitename-find"></span>
  <center><button class="fa fa-check-circle fa-3x submitbutton hvr-grow" type="submit"></button></center>
</form>
{% endblock %}

user/templates/user/profilecss.html
<style>
.contentboxbg {
  width:100%;
  height:200px;
  background:url('/media/{{ searcheduser.bgImg }}') no-repeat center;
}
</style>

user/templates/user/profiledetails.html
<!--
This renders the small section under the user's header image to display the user's username, displayname and 'view as...' buttons. Also displays semi transparent black footer if the user chooses 'view as' on their profile
-->

<div class="contentboxbg"></div>
<img src="/media/{{ searcheduser.profileImg }}" class="profileImg" />
<div class="contentboxdetails">
  <h1>{{ searcheduser.displayname }}</h1><span>@{{ searcheduser.username }}</span>
  <br/>{{ searcheduser.description }}
  <p class="viewas">
    {% if ownprofile %}
    <a href="{% url 'user:viewasconnected' %}">
      <button class="connectbutton orange hover-green">View as connected user</button>
    </a>
    <a href="{% url 'user:viewaspublic' %}">
      <button class="connectbutton orange hover-green">View as public</button>
    </a>

    {% endif %}
  </p>

  {% if viewas %}
  <div class="viewas-footer">
    {% if connected %}
      You are currently viewing as a connected user.
    {% else %}
      You are currently viewing as public.
    {% endif %}<br/>
    <a href="{% url 'user:index' %}" class="hvr-grow"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Return</a>
  </div>
  {% endif %}

user/templates/user/profilesearch.html
<!--
This page is only used if the user searches for another user or chooses 'view as...'
Handles the connection button to be displayed
-->

{% include 'user/profiledetails.html '%}

  {% if not ownprofile and request.session.loggedin %}
    {% if connected %}
    <p><form action="{% url 'user:disconnect' searcheduser.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="connectbutton green hover-red" id="connectedbutton" {% if viewas %}disabled{% endif %}><i class="fa fa-check" aria-hidden="true"></i><span> Connected</span></button>
    </form></p>
    {% else %}
        {% if notif == 2 %}
        <p><form action="{% url 'user:newconnect' searcheduser.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="connectbutton orange hover-green"><i class="fa fa-check" aria-hidden="true"></i> Accept request</button>
        </form></p>
        {% elif notif == 1 %}
        <p><form action="{% url 'user:cancelnotif' searcheduser.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="connectbutton green hover-red" id="requestsentbutton"><i class="fa fa-check" aria-hidden="true"></i><span> Request sent</span></button>
        </form></p>
        {% else %}
        <p><form action="{% url 'user:newnotif' searcheduser.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="connectbutton orange hover-green" {% if viewas %}disabled{% endif %}><i class="fa fa-plus" aria-hidden="true"></i> Connect</button>
        </form></p>
        {% endif %}
    {% endif %}
  {% endif %}
</div>

user/templates/user/search.html
{% extends 'main/layout.html' %}

{% block title %}{{ searcheduser.username }}'s profile {% endblock %}

{% if ownprofile %}
{% block outsidecontent %}{% include 'user/postlistform.html' %}{% endblock %}
{% endif %}

{% block css %}
  {% include 'user/profilecss.html' %}
{% endblock %}

{% block content %}

    {% include 'user/profilesearch.html '%}

    <div class="realcontent">
    {% if not request.session.loggedin and searcheduser.vis == 0 %}
        This user's account is private.
    {% elif not connected and searcheduser.vis == 0 %}
        This user's account is only visible to connected users.
    {% else %}
      {% include 'user/postlist.html' %}
    {% endif %}
    </div>

{% endblock %}

user/templates/user/searchnotfound.html
{% extends 'main/layout.html' %}

{% block title %}Connections {% endblock %}

{% block content %}
<div class="realcontent">
  <h1>User not found</h1>
  Sorry, the user you have searched for does not exist.
  <br/><br/>
  <form action="{% url 'user:searchuser' %}" method="get" class="styledform">
    <table><tr><td><input type="text" name="user_name" placeholder="Enter username to search" /></td><td><button class="fa fa-search fa-2x submitbutton hvr-float" type="submit"></button></td></tr></table>
  </form>
</div>
{% endblock %}