main/urls.py
from django.conf.urls import url

from . import views

app_name='main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^newuser/$', views.newuser, name='newuser'),
    url(r'^login/$', views.login, name='login'),
    url(r'^loginauth/$', views.loginauth, name='loginauth'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^resetpassword/$', views.resetpassword, name='resetpassword'),
    url(r'^(?P<user_id>[0-9]+)/resetauth/$', views.resetauth, name='resetauth'),
    url(r'^(?P<user_id>[0-9]+)/resetauthprocess/$', views.resetauthprocess, name='resetauthprocess'),
]

user/urls.py
from django.conf.urls import url

from . import views

app_name='user'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newpostform/$', views.newpostform, name='newpostform'),
    url(r'^(?P<post_id>[0-9]+)/newpostform/$', views.newpostformid, name='newpostformid'),
    url(r'^newpost/$', views.newpost, name='newpost'),
    url(r'^sitenamefind/$', views.sitenamefind, name='sitenamefind'),
    url(r'^sitenamelist/$', views.sitenamelist, name='sitenamelist'),
    url(r'^deletepost/$', views.deletepost, name='deletepost'),
    url(r'^(?P<user_id>[0-9]+)/$', views.search, name='search'),
    url(r'^search/$', views.searchuser, name='searchuser'),
    url(r'^viewaspublic/$', views.viewaspublic, name='viewaspublic'),
    url(r'^viewasconnected/$', views.viewasconnected, name='viewasconnected'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^customize/$', views.customize, name='customize'),
    url(r'^editsettings/$', views.editsettings, name='editsettings'),
    url(r'^editprofileimg/$', views.editprofileimg, name='editprofileimg'),
    url(r'^editbgimg/$', views.editbgimg, name='editbgimg'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^readnotifs/$', views.readnotifs, name='readnotifs'),
    url(r'^(?P<user_id>[0-9]+)/newnotif/$', views.newnotif, name='newnotif'),
    url(r'^(?P<user_id>[0-9]+)/cancelnotif/$', views.cancelnotif, name='cancelnotif'),
    url(r'^connections/$', views.connections, name='connections'),
    url(r'^get_status_twitter/$', views.get_status_twitter, name='get_status_twitter'),
    url(r'^(?P<user_id>[0-9]+)/newconnect/$', views.newconnect, name='newconnect'),
    url(r'^(?P<user_id>[0-9]+)/disconnect/$', views.disconnect, name='disconnect'),
    url(r'^custom/$', views.custom, name='custom'),
    url(r'^customsubmit/$', views.customsubmit, name='customsubmit'),
    url(r'^logout/$', views.logout, name='logout'),
]

webapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^user/', include('user.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

"""
    User:
    - Represents the accounts registered by the users within the application.

    Attributes:
    - username (unique)
    - password
    - email (unique)
    - displayname (not unique)
    - description
    - vis (integer field - public/1 or private/0)
    - profileImg
    - bgImg
    - useBg (unused attribute)
"""
class User(models.Model):
    VIS_CHOICES=(
        (1, 'Public'),
        (0, 'Private'),
    )
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField()
    displayname = models.CharField(max_length=50)
    description = models.CharField(max_length=200, blank=True)
    vis = models.PositiveSmallIntegerField(choices=VIS_CHOICES, default=1)
    profileImg = models.ImageField(upload_to='pic/', default = 'pic/default.jpg')
    bgImg = models.ImageField(upload_to='bg/', default = 'bg/default.jpg')  #change to imagefield?
    useBg = models.BooleanField()

    def __str__(self):
        return self.username

"""
    Post:
    - Represents the accounts of other site domains added by the users into their profiles.

    Attributes:
    - user (reference to user's ID as foreign key)
    - sitename (name of the site domain of the account added)
    - siteusername (username used on that site domain)
    - email (email used on that site domain - stored as a record of the user's login credential)
    - url
    - post_date (date of the latest update of the post)
    - usage (integer field - Most used/3, Moderately used/2, Least used/1, On hiatus/0)
    - description
    - vis (integer field - public/2, reserved/1, private/0)
    - logo
"""
class Post(models.Model):
    VIS_CHOICES=(
        (2, 'Public'),
        (1, 'Reserved'),
        (0, 'Private'),
    )
    USAGE_CHOICES=(
        (3, 'Most used'),
        (2, 'Moderately used'),
        (1, 'Least used'),
        (0, 'On hiatus'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sitename = models.CharField(max_length=50)
    siteusername = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True)
    url = models.URLField(blank=True)
    post_date = models.DateTimeField(auto_now=True)
    usage = models.PositiveSmallIntegerField(choices=USAGE_CHOICES, default=3)
    category = models.CharField(max_length=50, blank=True)
    description = models.CharField(max_length=100, blank=True)
    vis = models.PositiveSmallIntegerField(choices=VIS_CHOICES, default=2)
    logo = models.ImageField(upload_to='logo/', default = 'logo/default/pizza.png') #change to imagefield?

    def __str__(self):
        return str(self.id) + ' ' + self.sitename

    def was_posted_recently(self):
        return self.post_date >= timezone.now() - datetime.timedelta(days=1)

    def has_url(self):
        return bool(self.url)

    def has_email(self):
        return bool(self.email)

    def formatted_post_date(self):
        month = self.post_date.strftime('%b')
        day = str(self.post_date.day)
        result = month + " " + day
        return result


"""
    Notification
    - Generated when users send others a connection request or a connection request has been accepted.

    Attributes:
    - fromuser (id of the user who sent the connection request)
    - touser (id of the user who received the connection request)
    - is_read (boolean field)
    - is_accepted (boolean field)
    - notif_date (date of sending the connection request. This attribute is updated when the connection request is accepted. The new value is the date of which the request is accepted)
    - message (unused attribute)
"""
class Notification(models.Model):
    fromuser = models.PositiveIntegerField()
    touser = models.PositiveIntegerField()
    is_read = models.BooleanField(default=False)
    is_accepted = models.BooleanField(default=False)
    notif_date = models.DateTimeField(default=datetime.datetime.now())
    message = models.CharField(max_length=100)
    def __str__(self):
        return str(self.notif_date)

    def from_username(self):
        u = User.objects.get(id=self.fromuser)
        return u.username

    def to_username(self):
        u = User.objects.get(id=self.touser)
        return u.username

    def from_user_profileimg(self):
        u = User.objects.get(id=self.fromuser)
        return u.profileImg

    def to_user_profileimg(self):
        u = User.objects.get(id=self.touser)
        return u.profileImg


"""
    Connection
    - Represents the establishment of connection between two users.

    Attributes:
    - fromuser (id of the user who sent the connection request)
    - touser (id of the user who received and accepted the connection request)
"""
class Connection(models.Model):
    fromuser = models.PositiveIntegerField()
    touser = models.PositiveIntegerField()

main/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'username or email'}))
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

class ResetForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'username or email'}))

class NewPasswordForm(forms.Form):
    new_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings

from user.models import User
import user

from .forms import RegisterForm, LoginForm, ResetForm, NewPasswordForm

# Create your views here.

"""
    --- index(request) ---
    Returns a HttpResponse to display the main page.
"""
def index(request):
    template = loader.get_template('main/index.html')
    form = RegisterForm()
    try:
        u = user.views.getLoggedInUser(request)
    except User.DoesNotExist:
        return HttpResponse(template.render({}, request))
    notifNum = user.views.getUnreadNotifNum(request)
    return HttpResponse(template.render({'user': u, 'notifNum': notifNum, 'form': form}, request))

"""
    --- register(request) ---
    Returns a HttpResponse to display the registration page.
"""
def register(request):
    form = RegisterForm()
    try:
        u = User.objects.get(id=request.session['login_id'])
    except (KeyError, User.DoesNotExist):
        template = loader.get_template('main/register.html')
        return HttpResponse(template.render({'form': form}, request))
    #redirect if user is logged in
    return HttpResponseRedirect(reverse('user:index'))

"""
    --- newuser(request) ---
    Handles the request to create a new user.
    Redirects to the login page if a user is successfully created. The session variable 'register_success' is set to true.
    Otherwise, returns a HttpResponse to direct the user to registration page.
"""
def newuser(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        try:
            #check if there's a user with same username or email
            u = User.objects.get(Q(username__iexact=request.POST['username']) | Q(email=request.POST['email']))
        except (User.DoesNotExist): #if there is not... create a new user
            newuser = User(username=request.POST['username'], password=request.POST['password'], email=request.POST['email'], displayname=request.POST['username'], description="default description", vis=1, profileImg="pic/default.png", bgImg="bg/default.jpg", useBg=False)
            newuser.save()
            request.session['register_success'] = True
            return HttpResponseRedirect(reverse('main:login')) #... and redirect to login page
        #otherwise, redirect back to registration page with an error message
        return render(request, 'main/register.html', {
            'error_message': "The username or email is already in use. Please try again.",
            'form': form,
        })
    else:
        return render(request, 'main/register.html', {
            'error_message': "Please fill up the form.",
            'form': form,
        })


"""
    --- login(request) ---
    Returns a HttpResponse to display the login page.
"""
def login(request):
    form = LoginForm()
    message = user.views.getMessage(request, 'register_success', "Your new account has been successfully created.")
    try:
        u = User.objects.get(id=request.session['login_id'])
    except (KeyError, User.DoesNotExist):
        u = None
    template = loader.get_template('main/login.html')
    return HttpResponse(template.render({'user': u, 'form': form, 'message': message}, request))

"""
    --- loginauth(request) ---
    Handles the request to login. The input is compared against the usernames and emails in the database.
    Redirects to user:index page if login is successful.
    Otherwise, returns a HttpResponse to direct the user back to the login page.
"""
def loginauth(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        try:
            #check if there's a user with same username or email
            u = User.objects.get(Q(username__iexact=request.POST['username']) | Q(email=request.POST['username']))
        except (User.DoesNotExist): #if there is not... redirect to the login page
            return render(request, 'main/login.html', {
                'error_message': "This username or email does not exist. Did you enter it correctly?",
                'form': form,
            })

        #if user exists, check if the password match...
        if (u.password != request.POST['password']):
            return render(request, 'main/login.html', {
                'error_message': "The password was incorrect. Please try again.",
                'form': form,
            })
        #otherwise, return the profile page with login details
        request.session['login_id'] = u.id
        request.session['loggedin'] = True
        return HttpResponseRedirect(reverse('user:index'))
    else:
        return render(request, 'main/login.html', {
            'error_message': "Please fill up the form.",
            'form': form,
        })

"""
    --- reset(request) ---
    Returns a HttpResponse to display the reset password page.
"""
def reset(request):
    form = ResetForm()
    try:
        u = User.objects.get(id=request.session['login_id'])
    except (KeyError, User.DoesNotExist):
        u = None
        template = loader.get_template('main/resetpassword.html')
        return HttpResponse(template.render({'user': u, 'form': form,}, request))
    #redirect if user is logged in
    return HttpResponseRedirect(reverse('main:login'))


"""
    --- resetpassword(request) ---
    Handles the request to reset the user's password. (** currently no token is generated **) Sends an email to the user containing a link to reset the password.
    Directs the user back to reset password page after the request.
"""
def resetpassword(request):
    form = ResetForm(request.POST)
    if form.is_valid():
        try:
            u = User.objects.get(Q(username=request.POST['username']) | Q(email=request.POST['username']))
        except (User.DoesNotExist): #if there is not... redirect to the login page
            return render(request, 'main/resetpassword.html', {
                'error_message': "This username or email does not exist. Did you enter it correctly?",
                'form': form,
            })
        from_user = settings.EMAIL_HOST_USER
        subject = 'Password reset'
        message = resetmail(u.id)
        sender = 'Your web app'
        to = 'yeexin94ay@live.com' #change this to the user's email
        send_mail(subject, message, sender, ['yeexin94ay@live.com'], fail_silently=False)
        print("sending mail...")
        template = loader.get_template('main/resetpassword.html')
        return HttpResponse(template.render({'message': 'An email has been sent to ' + u.email, 'form': form,}, request))
    else:
        template = loader.get_template('main/resetpassword.html')
        return HttpResponse(template.render({'error_message': 'Please fill up the form.', 'form': form,}, request))


"""
    --- resetmail(request) ---
    Returns a HttpResponse that renders the email to be sent for password reset.
"""
def resetmail(user_id):
    u = User.objects.get(id=user_id)
    return loader.render_to_string('main/resetmail.html', {'user': u})


"""
    --- resetauth(request) ---
    Returns a HttpResponse to display the page for user to change their password for password reset.
"""
def resetauth(request, user_id):
    u = User.objects.get(id=user_id)
    form = NewPasswordForm()
    template = loader.get_template('main/resetauth.html')
    return HttpResponse(template.render({'user': u, 'form': form}, request))

"""
    --- resetauthprocess(request) ---
    Handles the request to change the user's password for password reset.
    Returns a HttpResponseRedirect to redirect the user to the login page if the password reset was successful.
    Otherwise, returns a HttpResponse to direct the user back to the change password page.
"""
def resetauthprocess(request, user_id):
    u = User.objects.get(id=user_id)
    form = NewPasswordForm(request.POST)
    if form.is_valid():
        u.password = request.POST['new_password'] #change the password
        u.save()
        return HttpResponseRedirect(reverse('main:login'))
    else:
        template = loader.get_template('main/resetauth.html')
        return HttpResponse(template.render({'user': u, 'form': form, 'error_message': 'Please fill up the form.'}, request))

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

  {% load staticfiles %}
  <link type="text/css" rel="stylesheet" href="{% static 'animate.css' %}" />
  <link type="text/css" rel="stylesheet" href="{% static 'hover.css' %}" />
  <link type="text/css" rel="stylesheet" href="{% static 'stylesheet.css' %}" />
  <link type="text/css" rel="stylesheet" href="{% static 'font-awesome-4.6.2/css/font-awesome.min.css' %}">
  <script src="{% static 'jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'wow.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'script.js' %}" type="text/javascript"></script>

  {% block js %}{% endblock %}
  {% block css %}{% endblock %}

</head>
<body>

{% block outsidecontent %}{% endblock %}

<div class="content{% block contentclass %}{% endblock %}">
<div class="header">
{% block header %}{% endblock %}
</div>

<div class="contentbox">

{% block content %}{% endblock %}

</div>
<!--
<div class="footer">
<center> footer :] </center>
</div>
-->
</div>

</body>
</html>

main/templates/main/index.html
{% extends 'main/layoutmain.html' %}

{% block title %}Main page {% endblock %}

{% block css %}

<style>
body {
  overflow:hidden;
  background-image:url('/media/{% if user %}{{ user.bgImg }}{% else %}bg/default.jpg{% endif %}');
  background-size:cover;
  background-repeat:no-repeat;
  background-attachment:fixed;
  background-origin:center;
  border:1px solid #000;
}

.content {
  margin-top:5%;
  text-align:center;
  z-index:10;
}

.loggedinbox {
  display:inline-block;
  width:80%;
  border-radius:20px;
  background-color: rgba(228,228,228,0.9);
  margin-bottom:0px;
}

@media screen and (max-width:600px) {
  .mainbox {
    font-size:0.8em;
  }
  .loggedinbox p {
    margin:0px;
  }

  .loggedinbox {
    border-radius:0px;
    width:100%;
  }
}
</style>
{% endblock %}

{% block outsidecontent %}
<div class="overlay">
  <div class="overlay-black"></div>
    <div class="content animated fadeInUp">
      {% if request.session.loggedin %}
        {% include 'main/loggedinbox.html' %}
      {% else %}
        <div class="mainbox">
          <h1 class="maintitle">Cobweb</h1>
          <p>Connect with others through your many web accounts.</p>
        </div>
      <div class="mainbox">
        <!-- duplicated codes-->
          <form action="{% url 'main:newuser' %}" method="post">
          {% csrf_token %}
          <div class="styledform">
          <table>{{ form.as_table }}</table>
          </div>
          <center><button type="submit" class="submitbutton hvr-bob"><span class="buttonleftfont oswald-font">Register</span> <i class="fa fa-chevron-circle-right fa-2x"></i></button></center>
          </form>
          <!-- -->
        <p>Already have an account? <a href="{% url 'main:login' %}">Login</a></p>
      </div>
      {% endif %}
<!--
  <div class="wow fadeInUp mainbox">
    <i class="fa fa-asterisk fa-4x fa-border orange-text leftbox" aria-hidden="true"></i>
    <h1 class="title">Link your accounts to one place</h1>
    <p>Have your many online accounts accessible from one single page.
    </p>
  </div>

  <div class="wow fadeInUp mainbox">
    <i class="fa fa-info-circle fa-4x fa-border orange-text leftbox" aria-hidden="true"></i>
    <h1 class="title">Include your details</h1>
    <p>Include your account credentials and descriptions to let others know where to find you.</p>
  </div>

  <div class="wow fadeInUp mainbox">
    <i class="fa fa-users fa-4x fa-border orange-text leftbox" aria-hidden="true"></i>
    <h1 class="title">Connect with others</h1>
    <p>Connect with your peers. Present your information differently to strangers, to your friends and to yourself.</p>
  </div>
-->
</div>
</div>
{% endblock %}

{% block contentclass %} hidden{% endblock %}

main/templates/main/layout.html
{% extends 'main/base.html' %}

{% block header %}
{% if request.session.login_id %}
  <div class="header-leftbar">
    <img src="/media/{{ user.profileImg }}" class="profileImg">
    <span class="greeting">Hi, <a href="{% url 'user:index' %}">{{ user.displayname }}</a></span><br/>
    <span class="header-links">
    <a href="{% url 'main:index' %}" class="hvr-grow">Home <i class="fa fa-home" aria-hidden="true"></i></a>
    <a href="{% url 'user:notifications' %}" class="hvr-grow link-margin-left">Notifications <i class="fa fa-envelope" aria-hidden="true"></i> {% if notifNum != 0 %}{{ notifNum }}{% endif %}</a>
    </span>
  </div><div class="header-rightbar">
  <form action="{% url 'user:searchuser' %}" method="get">
    <input type="text" name="user_name" placeholder="Search a user..." />
    <button class="fa fa-search submitbutton white-search hvr-float" type="submit"></button>
  </form><span class="header-links">
  <a href="{% url 'user:connections' %}" class="hvr-grow link-margin-right">Connections <i class="fa fa-coffee" aria-hidden="true"></i></a>
  <a href="{% url 'user:settings' %}" class="hvr-grow link-margin-right">Settings <i class="fa fa-cog" aria-hidden="true"></i></a>
  <a href="{% url 'user:logout' %}" class="hvr-grow link-margin-right">Logout <i class="fa fa-sign-out" aria-hidden="true"></i></a>
</span>
  </div>
{% else %}
<div class="header-rightbar">
  <form action="{% url 'user:searchuser' %}" method="get">
    <input type="text" name="user_name" placeholder="Search a user..." />
    <button class="fa fa-search submitbutton white-search hvr-float" type="submit"></button>
  </form><span class="header-links">
  <a href="{% url 'main:index' %}" class="hvr-grow link-margin-right">Home <i class="fa fa-home" aria-hidden="true"></i></a>
  <a href="{% url 'main:register' %}" class="hvr-grow link-margin-right">Register <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
  <a href="{% url 'main:login' %}" class="hvr-grow link-margin-right">Login <i class="fa fa-sign-in" aria-hidden="true"></i></a></span>
</div>
{% endif %}
{% endblock %}

main/templates/main/layoutmain.html
{% extends 'main/base.html' %}

{% block header %}
  <center><a href="{% url 'main:index' %}"><h1 class="maintitle hvr-grow">Cobweb</h1></a></center>
{% endblock %}

main/templates/main/loggedinbox.html
<div class="loggedinbox">
  <img src="/media/{{user.profileImg}}"/>
  <h1>Hi, {{ user.displayname }}!</h1>
  <p>You have a total of {{ user.post_set.all.count }} accounts listed on your profile.</p>
  <br />
  <p><a href="{% url 'user:index' %}" class="hvr-bob">Go to your profile <i class="fa fa-chevron-circle-right fa-1x" aria-hidden="true"></i></a></p>
</div><div class="mainbox logoutbox">
  <p><a href="{% url 'user:logout' %}" class="hvr-bob"><i class="fa fa-chevron-circle-left fa-1x" aria-hidden="true"></i> Logout</a></p>
</div>

main/templates/main/login.html
{% extends 'main/layoutmain.html' %}

{% block title %}Login {% endblock %}

{% block content %}
<div class="realcontent">
  <h1>{% if request.session.loggedin %}You're already logged in{% else %}Login{% endif %}</h1>
  {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
  {% if message %}<p class="message">{{ message }}</p>{% endif %}
  {% if request.session.loggedin %}
  {% include 'main/loggedinbox.html' %}
  {% else %}
      <form action="{% url 'main:loginauth' %}" method="post">
      {% csrf_token %}
      <div class="styledform">
      <table>{{ form.as_table }}</table>
      </div>
      <center><button type="submit" class="submitbutton hvr-grow"><span class="buttonleftfont oswald-font">Login</span> <i class="fa fa-chevron-circle-right fa-2x"></i></button>
      <p><a href="{% url 'main:reset' %}">Forgot your password?</a></p></center>
      </form>
  {% endif %}
  </div>
{% endblock %}

main/templates/main/register.html
{% extends 'main/layoutmain.html' %}

{% block title %}Register {% endblock %}

{% block content %}
<div class="realcontent">
  <h1>Register</h1>
  {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
    <form action="{% url 'main:newuser' %}" method="post">
    {% csrf_token %}
    <div class="styledform">
    <table>{{ form.as_table }}</table>
    </div>
    <center><button type="submit" class="submitbutton hvr-grow"><span class="buttonleftfont oswald-font">Register</span> <i class="fa fa-chevron-circle-right fa-2x"></i></button></center>
    </form>
  </div>
{% endblock %}

main/templates/main/resetauth.html
{% extends 'main/layoutmain.html' %}

{% block title %}Reset password {% endblock %}

{% block content %}
<div class="realcontent">
  <h1>Reset password</h1>
  {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
  <form action="{% url 'main:resetauthprocess' user.id %}" method="post">
  {% csrf_token %}
  <div class="styledform">
  <table>{{ form.as_table }}</table>
  </div>
  <center><button type="submit" class="submitbutton hvr-grow"><span class="buttonleftfont oswald-font">Change your password</span> <i class="fa fa-chevron-circle-right fa-2x"></i></center>
  </form>
</div>
{% endblock %}

main/templates/main/resetmail.html
A password reset for {{ user.username }} has been requested.
Reset your password here: http://127.0.0.1:8000{% url 'main:resetauth' user.id %}

main/templates/main/resetpassword.html
{% extends 'main/layoutmain.html' %}

{% block title %}Reset password {% endblock %}

{% block content %}
<div class="realcontent">
  <h1>Reset password</h1>
  {% if error_message %}<p class="error-message">{{ error_message }}</p>{% endif %}
  {% if message %}<p class="message">{{ message }}</p>{% endif %}
  <form action="{% url 'main:resetpassword' %}" method="post">
  {% csrf_token %}
  <div class="styledform">
  <table>{{ form.as_table }}</table>
  </div>
  <center><button type="submit" class="submitbutton hvr-grow"><span class="buttonleftfont oswald-font">Reset</span> <i class="fa fa-chevron-circle-right fa-2x"></i></center>
  </form>
</div>
{% endblock %}